#!/usr/bin/env bash
# Script which configures an Ubuntu server as shown below:
# **** localhost  127.0.0.2
# **** facebook.com 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/		 ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
